/*
 * This source file was generated by the Gradle 'init' task
 */
package org.andreistrogonov;

import org.andreistrogonov.annotations.ToDouble;

public class Library {
    @ToDouble(defaultValue = 123.45)
    public double toDouble() {
        return 456.78;
    }
}


