/*
 * This source file was generated by the Gradle 'init' task
 */
package org.andreistrogonov;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PythonAnnotationsTest {
    // Method returns the expected double value 456.78
    @Test
    public void test_to_double_returns_expected_value() {
        Library library = new Library();

        double result = library.toDouble();

        assertEquals(456.78, result, 0.001);
    }


}
